server: 
  port: 4003

eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka/eureka
  instance:
    preferIpAddress: true